# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Bren Blogs
tagline:          'An amazing blog'
description:      'An example blog created with help from Github-Pages</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Brenden Malacara'
  url:            https://twitter.com/brenwrenhawk

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/brenwrenhawk/brenwrenhawk.github.io
